spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_db
    username: postgres
    password: Alex!123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: payment-service
server:
  port: 8082